name: crawl

on:
  workflow_dispatch:
  schedule:
    # every saturday 12pm GMT+7
    - cron: 0 5 * * SAT,WED

jobs:
  main:
    runs-on: ubuntu-latest
    environment: GREATMIND
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install python dependencies
        run: pip install lxml requests sqlite3worker algoliasearch
      - name: Crawl step 1
        run: python crawler.py --crawl-step-1
      - name: Crawl step 2
        run: python crawler.py --crawl-step-2
      - name: Algolia re-index
        run: python algolia.py
      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "crawl and update content" ||  true
          git push --force origin HEAD:$GITHUB_REF || true
